// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type UpdateUser struct {
	FirstName  string `json:"firstName"`
	LastName   string `json:"lastName"`
	MiddleName string `json:"middleName"`
}

type User struct {
	ID         string `json:"id"`
	FirstName  string `json:"firstName"`
	LastName   string `json:"lastName"`
	MiddleName string `json:"middleName"`
	Phone      string `json:"phone"`
}
